# wrangler.toml
name = '2026cm0404'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "2026cm.6cm.us.ci"				#KV数据库id
